<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Station;
use Doctrine\ORM\EntityRepository;

/**
 * BikesAvailableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BikesAvailableRepository extends EntityRepository
{
    /**
     * @param Station $station
     * @param \DateTime $start
     * @param null $end
     * @return array
     */
    public function findBikesByDate(Station $station, \DateTime $start, $end = null){
        $qb = $this->createQueryBuilder('b');

        $qb
            ->where('b.createdAt >= :start')
            ->setParameter('start', $start)
            ->andWhere('b.station = :station')
            ->setParameter('station', $station)
        ;

        if ($end){
            $qb
                ->andWhere('b.createdAt <= :end')
                ->setParameter('end', $end)
            ;
        }

        return $qb->getQuery()->getResult();
    }

    /**
     * @param Station $station
     *
     * @return array
     */
    public function findTodayAvailability(Station $station){
        $qb = $this->createQueryBuilder('b');

        $qb
            ->where('b.createdAt >= :start')
            ->setParameter('start', new \DateTime(date('Y-m-d')))
            ->andWhere('b.station = :station')
            ->setParameter('station', $station)
        ;

        return $qb->getQuery()->getResult();
    }

    /**
     * @param \DateTime $start
     *
     * @return array
     */
    public function findOldDataByDate(\DateTime $start){
        $qb = $this->createQueryBuilder('b');

        $qb
            ->where('b.createdAt < :start')
            ->setParameter('start', $start)
        ;

        return $qb->getQuery()->getResult();
    }
}
