app:
    resource: "@AppBundle/Controller/"
    type:     annotation

api :
  type : rest
  resource : "@AppBundle/Resources/config/routing.yml"
  prefix : /api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
